server:
    port: 9091
    context-path: /product-api
spring:
    thymeleaf:
        cache: false
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.10.10.109:3306/fuyutong_auction
        username: root
        password: MyNewPass1!
    # Redis
    redis:
        # 数据库索引（默认为0
        database: 0
        # 服务器地址
        host: 10.10.10.108
        # 服务器连接端口
        port: 6379
        # 服务器连接密码（默认为空）
        password:
        #连接池
        pool:
            # 最大连接数（使用负值表示没有限制）
            max-active: 8
            # 最大阻塞等待时间（使用负值表示没有限制）
            max-wait: -1
            # 最大空闲连接
            max-idle: 8
            # 最小空闲连接
            min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 0
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 1Mb      # Max file size，默认1M
            max-request-size: 1Mb   # Max request size，默认10M
    jpa:
        database: MYSQL
        hibernate:
            # 自动更新表
            ddl-auto: update  # 第一次建表create  后面用update
            # Naming strategy
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        #显示sql语句
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect